version: "3.7"
services:
  maplebot:
    container_name: maplebot
    build: .
    image: maplebot
    hostname: maplebot
    restart: always
    tty: true
    stop_signal: SIGINT
    network_mode: bridge
    volumes:
      - "/opt/maplebot/config:/maplebot/config"
      - "/opt/maplebot/logs:/maplebot/logs"
    environment:
      TZ: "America/Chicago"